jdk: oraclejdk8

language: java

sudo: false

install: true

addons:
  sonarcloud:
    organization: "cloudyrock"
    token:
      secure: $SONAR_TOKEN

cache:
  directories:
  - "$HOME/.m2/repository"

after_success:
  - mvn sonar:sonar